name: Release

on:
  push:
    branches:
      - fix-settings
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run build script
      run: |
        ./build.sh "$GITHUB_REF_NAME";
        ls -l
        ls -l ../
    
    - name: Create release notes
      run: git tag -l --format='%(contents:subject)' v0.8.6 > release-notes.txt

    - name: Create Release
      id: create-release
      uses: ncipollo/release-action@v1
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        POSTFIX: ${{ github.ref_name }}
      with:
        artifacts: "../polyglotter-$POSTFIX.xpi"
        draft: false
        bodyFile: "./release-notes.txt"
        makeLatest: true
        tag: v.1.4-debug
        commit: fix-settings